-- This should be autogenerated and diffed against existing things, 
-- otherwise it's too cumbersome (aka header files, but in another language).
create procedure HelloWorldProc_HelloWorld
@a nchar(25) output
as
external name TestProject.HelloWorldProc.HelloWorld

declare @J nchar(25)  
exec HelloWorldProc_HelloWorld @J out  
print @J