-- This should be autogenerated and diffed against existing things, 
-- otherwise it's too cumbersome (aka header files, but in another language).
create or alter procedure Test_Stuff
as
external name TestProject.Test.Stuff
go

exec Test_Stuff
go
